### ISSUE TITLE
Error running test_model.py

### ISSUE THREAD

**Issue by frank-y-liu** [metalbubble/moments_models#7]
I ran into the following error message:

```
Traceback (most recent call last):
  File "test_model.py", line 64, in <module>
    model = load_model(modelID, categories)
  File "test_model.py", line 33, in load_model
    state_dict = {str.replace(k, 'module.', ''): v for k, v in checkpoint['state_dict'].items()}
  File "test_model.py", line 33, in <dictcomp>
    state_dict = {str.replace(k, 'module.', ''): v for k, v in checkpoint['state_dict'].items()}
TypeError: descriptor 'replace' requires a 'str' object but received a 'unicode'
```
My guess is that it's related to python27(which I am using) and python36. Do you have a version of the code tested on python27?

**Comment by metalbubble** [comment]
model is trained and tested on python36. Please update your python to the correct version. Thanks.
